### ISSUE TITLE
Processing multiple files

### ISSUE THREAD

**Issue by zoka123** [forikal-uk/gsheet-to-xml#2]
When processing a single file with multiple tabs, each tab is serialized as a single `<Inventory>` element.

How should we process multiple files (with potentially multiple tabs)?
Should I merge all inventories from all files or create different `<Product>` node for every file?

**Comment by forikal-uk** [comment]
There is only ever one `<Inventory>` element per `<Product>` element. 

Each Google Sheet tab represents one of these: `<Product><Inventory>...data here..</Inventory></Product>`.

This was not very clear from [my example XML](https://github.com/forikal-uk/xml-authoring-project/commit/cd697c598a37db5f0792551d87758b8b511c5751#diff-66b63af35350311da15a4241f8111b62) so I will update that. 

(The word `Product` is a bit confusing because it really means `Instance Of A Client Contract`. I will have to arrange for that name to be refactored better. But for now we have to make do with it).

So, when processing a single file with multiple tabs, each tab should be treated as a separate `<Product><Inventory>` element.

and when processing multiple files (with potentially multiple tabs) each tab should, again, be treated as a separate `<Product><Inventory>` element.
